export type Quiz = {
  _id: string;
  title: string;
  description: string;
  status: string;
  availability: string;
  points: number;
  quizType: string;
  assignmentGroup: string;
  shuffleAnswers: boolean;
  multipleAttempts: boolean;
  showOneQuestionAtATime: boolean;
  webcamRequired: boolean;
  lockQuestionsAfterAnswering: boolean;
  showCorrectAnswers: boolean;
  accessCode?: string;
  questions: number;
  timeLimitMinutes: number;
  availableFrom: string | Date;
  availableUntil: string | Date;
};
